Get-FrenchRepublicanDate.ps1
=> 🐛Spelling mistakes in `Get-FrenchRepublicanDate`

Add-GitHubMetadata.ps1, ConvertFrom-Base64.ps1, Format-ByteUnits.ps1, Get-Unicode.ps1, test/Convert-ClipboardTsvToHtml.Tests.ps1
=> 🎨 Use `*` operator for more idiomatic char/string repetition

Export-Json.ps1, Select-Json.ps1
=> ✨ JSON scripts that accept paths should support wildcards

Select-Json.ps1, test/Select-Json.Tests.ps1
=> 🐛 Select-Json.ps1 fails to select within arrays property

ConvertTo-PowerShell.ps1
=> 🐛 ConvertTo-PowerShell.ps1 should encode nonprintable characters correctly

.github/workflows/jekyll-gh-pages.yml, Export-Readme.ps1, README.md, docs/Export-Readme.ps1.md, docs/Export-TableMerge.ps1.md, docs/Show-PSDriveUsage.ps1.md, docs/index.md
=> 👨‍💻⚗ Make Export-Readme.ps1 cross-platform and revisit the dependency chart

.github/workflows/pester.yml, Update-Everything.ps1
=> ✨ Add VSCode extensions to Update-Everything.ps1

dataref.css, dataref.xslt
=> 🐛 The dataref.xslt transform has some bugs

Use-Command.ps1
=> ⚗ Investigate making Use-Command.ps1 more cross-platform

Get-ADServiceAccountInfo.ps1
=> 🎨 Get-ADServiceAccountInfo.ps1 should lookup the computers

Get-SimpleSchTasks.ps1
=> 🐛 Get-SimpleSchTasks.ps1 missing Enabled property error

Get-SimpleSchTasks.ps1
=> 🐛 Get-SimpleSchTasks.ps1 not providing a recurrence Schedule value for some triggers

Trace-WebRequest.ps1
=> 🐛 Trace-WebRequest.ps1 doesn't follow relative URLs correctly

Measure-Properties.ps1
=> ✨ Add Measure-Properties.ps1

Trace-WebRequest.ps1
=> ✨ Trace-WebRequest.ps1 should add certificate details

Get-SimpleSchTasks.ps1
=> ✨ Get-SimpleSchTasks.ps1 should include last run result

Repair-MarkdownHeaders.ps1, test/data/rehead.md
=> ✨ Add script to correct markdown headers

Get-CachedCommand.ps1, Get-PathUsage.ps1
=> ✨ Get-CachedCommand.ps1  & Get-PathUsage.ps1

Get-ModuleScope.ps1, Update-Everything.ps1
=> ✨ Handle special cases when upgrading PowerShell modules in Update-Everything.ps1

Update-Everything.ps1
=> ✨ Update-Everything.ps1 PSModule section should be aware of install scope
